# Site wide configuration

title:            Blog
locale:           en_US
url:              ""


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Erica Lynn Rodriguez
  avatar: bio-photo.jpg
  bio: "Designer with a new found passion for front-end web development"
  email:
  disqus-shortname: ericalynnrodriguez
  twitter: eddyca_erica
  facebook: eddycaaa
  google:
    plus: #username
    analytics: UA-61410513-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: eddyca
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: ericalynnrodriguez
  xing: #username
  instagram: eddyca
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: photos/duchess_of_candied_apples/sets/

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
